# Generated by Django 3.2.9 on 2022-04-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_myproductsmodel_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproductsmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
