# Generated by Django 3.2.9 on 2022-05-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_myproductsmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproductsmodel',
            name='price',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
    ]
