# Generated by Django 3.2.9 on 2022-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_myproductsmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproductsmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
