# Generated by Django 3.2.9 on 2022-05-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_for_diller',
            name='price',
            field=models.IntegerField(blank=True, default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_for_diller',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
